# Docker para desarrollo
FROM golang:1.14.3-buster

WORKDIR /go/src/statsv0

RUN go get github.com/derekparker/delve/cmd/dlv

ENV REDIS_URL host.docker.internal:6379
ENV RABBIT_URL amqp://host.docker.internal
ENV AUTH_SERVICE_URL http://host.docker.internal:3000

EXPOSE 3010 40010

CMD ["dlv", "debug", "--listen=:40001", "--headless=true", "--api-version=2", "--log"]
